### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#11]
## 구현 내용
- [x] data layer
    - [x] User data class 생성 (Mapper 메서드 추가)
    - [x] Result data class 생성
    - [x] Repository, DataSource 구현
    - [x] Retrofit Service 생성
    - [x] Hilt Module 생성
- [x] ui layer
    - [x] User data class 생성
    - [x] SignUpContract 생성
    - [x] SignUpViewModel 생성
    - [x] Hilt Module 생성
    - [x] 회원가입 UI에서의 구현

### TODO
- domain layer UseCase 사용 고려
