### ISSUE TITLE
회원가입 기능 추가 개선

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#16]
## 구현 내용
- [x] 전화번호 입력 자동 하이픈(-) 적용
- [x] 미입력 TextField error 표시
- [x] 이메일, 비밀번호 정규식 적용
- [x] 주소 필드 삭제
- [x] UiState 구조 개선
    - TextField별 성공, 오류 상태, 오류 메시지

### TODO
- TextField별 성공, 오류 상태, 오류 메시지가 사라지지 않는 버그 수정
- 이메일, 별명 중복확인 구현 (Debouncing)
- 생년월일 DatePicker 적용 고려
