### ISSUE TITLE
Album UI 수정

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#30]
## Issue
- [x] Coil Compose Dependency 추가
- [x] AlbumItem, AlbumItemCard 수정
    - [x] 대표 이미지 (Coil - 임시 이미지 주소)
    - [x] 타이틀
    - [x] 서브타이틀

### TODO
- 앨범 조회 기능 연동
