### ISSUE TITLE
AlbumDetail 화면 수정 & 기능 연결

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#45]
## 앨범 디테일 화면 수정
- [x] 서브 앨범 대표사진 Grid 구현
- [x] 멤버 권한 폰트 색상 적용
- [x] 서브앨범 삭제 기능
- [x] 멤버 수정(추방) 기능
- [x] 앨범 설정 목록 클릭 시 해당 기능 화면으로 이동해 수정할 수 있도록 구현
    - [x] 멤버는 앨범 나가기만
    - [x] 앨범 대표 이미지 업로드 - 갤러리에서 선택

## 앨범 기능 연결
- [x] 앨범 설정 기능 연결 (앨범 이미지, 타이틀, 서브타이틀 수정, 앨범 삭제)
- [x] 서브 앨범 기능 구현, 연결
- [x] 멤버 기능 구현, 연결

### TODO
- URL 수정, Retrofit 파라미터 수정
