### ISSUE TITLE
앨범 목록 조회 기능 구현, 연결

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#52]
## 앨범 목록 조회 기능 구현, 연결
- [x] 앨범 목록 조회 기능 구현 (Data, Domain Layer)
- [x] AlbumScreen 앨범 목록 표시 (UI Layer)
    - [x] Coil Image
    - [x] 타이틀, 서브 타이틀

### TODO
-  Album 정보 AlbumDetail 화면으로 전달 (Navigation Argument)
