### ISSUE TITLE
AlbumDetail 테스트 후 문제 수정

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#66]
## AlbumDetail 작업 완료 후 테스트, 문제 수정
- [x] 로그인, 회원가입 수정
    - [x] 기능 주석처리 해제
    - [x] Json -> FormUrlEncoded 수정
- [x] 파라미터 변경사항, 잘못 기재한 내용 수정
- [x] DELETE 메서드에 Body가 있는 경우의 어노테이션 수정

### TODO
- 서브 앨범 삭제 -  HTTP 500 오류 해결
- 앨범 삭제 or 나가기 이후 앨범 목록 갱신되지 않는 문제 해결
