### ISSUE TITLE
MVI Base 구현

### ISSUE THREAD

**Issue by eoeo0326** [Momentwo/Momentwo#9]
## 구현 내용
- [x] BaseViewModel 구현
    - [x] UiState, UiEvent, UiEffect Interface 생성
    - [x] uiState, event, effect Flow 생성 (Backing Properties)
    - [x] state 초기화 메서드 구현
    - [x] state, event, effect Set 메서드 구현
    - [x] event collect, handle 메서드 구현
- [x] AlbumContract 구현
- [x] AlbumViewModel 구현
    - [x] state 초기화 메서드, event handle 메서드 override

### 참고
https://velog.io/@moonliam_/Android-MVI-Pattern-1
https://velog.io/@seunghee17/Compose는-MVI를-좋아해

### TODO
- Orbit 학습, 사용 고려
